[phases.setup]
nixPkgs = ["python3", "nodejs_18"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm ci",
    "cd frontend && npm run build"
]

[phases.build]
cmds = [
    "cd backend && python init_db.py"
]

[start]
cmd = "cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT"